version: "2"

services:
    web:
        image: nginx:latest
        restart: always
        network_mode: "bridge"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf/nginx/drupal.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
          - php
        links:
          - php
        environment:
          - VIRTUAL_HOST=abcd.yongbuzhixi.com
          - LETSENCRYPT_HOST=abcd.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com
    
    php:
        image: drupal:7-fpm
        restart: always
        network_mode: "bridge"
        volumes:
          - "./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro"
          - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
          - /var/www/html/
          - "./code/sites/all:/var/www/html/sites/all"
          - "./code/sites/default/settings.php:/var/www/html/sites/default/settings.php:rw"
          - "./code/sites/default/files:/var/www/html/sites/default/files:rw"
          # - ".HACK core"
          - "./code/includes/file.inc:/var/www/html/includes/file.inc"
