version: "2"

services:
    web:
        image: nginx:latest
        restart: always
        network_mode: "bridge"
        # networks:
        #   static-network:
        #     ipv4_address: 172.17.0.251
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            #- ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/drupal.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/amplify.conf:/etc/nginx/conf.d/amplify.conf
        volumes_from:
          - storage-drupal
        links:
            - php
        #work with jwilder/nginx-proxy
        # ports:
        #     - "8080"
        environment:
          - VIRTUAL_HOST=www.abc-chinaedu.com,abc.vultr.yongbuzhixi.com
          - LETSENCRYPT_HOST=www.abc-chinaedu.com,abc.vultr.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com
    
    #api-code-app > drupal:fpm > php:7-fpm 只执行一次！！！
    php:
        image: drupal:7-fpm
        # image: drupal-php7-fpm #给build镜像后的image命名
        restart: always
        network_mode: "bridge"
        links:
          - "db"
        volumes_from:
          - storage-drupal
        volumes:
          - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
          - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    db:
      image: mariadb:latest
      # container_name: mysql #Specify a custom container name, rather than a generated default name.
      restart: always
      network_mode: "bridge"
      volumes:
        - ./sql:/sql
      volumes_from:
        - storage-drupal
      environment:
        - MYSQL_USER=abc
        - MYSQL_PASSWORD=abc
        - MYSQL_DATABASE=abc
        - MYSQL_ROOT_PASSWORD=abc

    #################
    storage-drupal:
      build: ./code
      # image: drupal-storage
      network_mode: "bridge"
      # container_name: storagedrupal
      command: ["echo","create_only"]
      # command: ["chmod","-R","777","/var/www/html/sites/default/files"] #v3# create_only: true
      # volumes:
      #   - ./code:/code
        # - /var/www/html/sites/default/files
      volumes_from:
        - files-drupal
    files-drupal:
      image: drupal:7-fpm
      network_mode: "bridge"
      command: ["chmod","-R","777","/var/www/html/sites/default/files"] #create_only: never update!
      volumes:
        - /var/lib/mysql
        - /var/www/html/sites/default
        - ./code/sites/default/settings.php:/var/www/html/sites/default/settings.php
        - /var/www/html/sites/default/files